const BLACKLINE_CONFIG = {
    repairItems: [
        { name: "Abschleppen ab Route 68", price: 0 },
        { name: "Abschleppen bis Route 68", price: 0 },
        { name: "Achse", price: 0 },
        { name: "Airbag", price: 0 },
        { name: "Anfahrtspauschale", price: 0 },
        { name: "Antriebsachse", price: 0 },
        { name: "Arbeitslohn", price: 150 },
        { name: "Ausbeulen", price: 95 },
        { name: "Auspuff", price: 0 },
        { name: "Au&szlig;enspiegel", price: 0 },
        { name: "Batterie", price: 0 },
        { name: "Begleitung Schwertransport", price: 0 },
        { name: "Benzinkanister", price: 0 },
        { name: "Boottransport (klein)", price: 0 },
        { name: "Boottransport (gro&szlig;)", price: 0 },
        { name: "Bremsen", price: 0 },
        { name: "Dach", price: 0 },
        { name: "Einschussloch", price: 0 },
        { name: "Federung", price: 0 },
        { name: "Felge (pro Stck)", price: 0 },
        { name: "Folie ausbessern", price: 0 },
        { name: "Getriebe", price: 0 },
        { name: "Gutachten", price: 500 },
        { name: "Innenrauminstand.", price: 900 },
        { name: "Kleinteile (Schrauben etc.)", price: 20 },
        { name: "Kofferraumdeckel", price: 0 },
        { name: "Kotfl&uuml;gel", price: 0 },
        { name: "K&uuml;hler", price: 0 },
        { name: "K&uuml;hler / Mittel", price: 0 },
        { name: "K&uuml;hlergrill", price: 0 },
        { name: "Lack ausbessern", price: 35 },
        { name: "Leitungen (Benzin, Brems, etc)", price: 0 },
        { name: "Lenkrad", price: 0 },
        { name: "Motor", price: 0 },
        { name: "Motor entw&auml;ssern", price: 0 },
        { name: "Motorhaube", price: 0 },
        { name: "&Ouml;l / &Ouml;lwanne", price: 0 },
        { name: "Politur pro Fahrzeug", price: 0 },
        { name: "Radaufh&auml;ngung", price: 0 },
        { name: "Reifen (pro Stck)", price: 0 },
        { name: "Scheibe (Front)", price: 0 },
        { name: "Scheibe (Heck)", price: 0 },
        { name: "Scheibe (Seite)", price: 0 },
        { name: "Scheibenwischer", price: 0 },
        { name: "Scheinwerfer (pro Stck.)", price: 0 },
        { name: "Sitz (pro Stk.)", price: 0 },
        { name: "Spoiler", price: 0 },
        { name: "Sto&szlig;stange (Hinten)", price: 0 },
        { name: "Sto&szlig;stange (Vorne)", price: 0 },
        { name: "Tank aussaugen", price: 0 },
        { name: "Trittbrett", price: 0 },
        { name: "T&uuml;r", price: 0 },
        { name: "T&uuml;rschlo&szlig;", price: 100 },
        { name: "&Uuml;berrollb&uuml;gel", price: 0 },
        { name: "Unterboden", price: 0 },
        { name: "Z&uuml;ndkerze", price: 0 }
    ]
};
